version: '2'
services:
    web:
        build: ./main
        ports:
            - "5000:80"
        volumes:
            - ./main:/code
        depends_on:
            - redis
    sub:
        build: ./sub
        ports:
            - "5001:80"
        volumes:
            - ./sub:/code
        depends_on:
            - redis
    redis:
        image: redis
